# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5d699d66352050d7b03af044c32e3febb35fcc82c7085c276580effd24ece70ad29458e94d9f9f3915773d7bbbeb425891531eba205462678f730b00c5b4591c

test:
  secret_key_base: bd567577fb6c03b2470b2020b8a555a23a74a0b7050b5d5e125167e54b8df083ba8fc316264572207bd9457ac8625a3d6c7a40d074a4b715237813f69f8e9f87

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
